# Generated by Django 5.2.14 on 2026-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
