# Generated by Django 5.2.14 on 2026-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('need_more_information', 'Need More Information'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
